EtatSituation/Controllers/EdsArchiveController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using EtatSituation.Models;
using EtatSituation.API;
using System.Web.UI.WebControls;

namespace EtatSituation.Controllers
{

    public class EdsArchiveController : Controller
    {
        public async Task<JsonResult> ChargementDonnees()
        {
            List<EdsDonnees> result = Eds.ObtenirDonneesEDSArchive("911", "2020-08-06T00:00:00");

            return Json(new
            {
                CarteAppel = result.Where(a => a.Indicateur.Contains("CarteAppel")).ToList(),
                VehDevoir = result.Where(a => a.Indicateur.Contains("VehDevoir")).ToList(), 
                AppelsAttenteAff = result.Where(a => a.Indicateur.Contains("AppelsAttenteAff")).ToList(),
                VolumeAppel = result.Where(a => a.Indicateur.Contains("VolumeAppel")).ToList(),
                SDDF = result.Where(a => a.Indicateur.Contains("SDDF")).ToList(),
                Ratio = result.Where(a => a.Indicateur.Contains("Ratio")).ToList(),
                //ActionPreventive = result.Where(a => a.Indicateur.Contains("ActionPreventive")).ToList(),
                QuotaEffectifs = result.Where(a => a.Indicateur.Contains("QuotaEffectifs")).ToList()
            });
        }

        public async Task<JsonResult> ChargementMeteo()
        {
            Meteo.MeteoResult meteoResult = Eds.ObtenirMeteo();

            return Json(new
            {
                icon = meteoResult.currently.icon,
                summary = meteoResult.currently.summary,
                temperature = meteoResult.currently.temperature,
                apparentTemperature = meteoResult.currently.apparentTemperature
            });

        }

        // GET: EdsArchive
        public ActionResult Index()
        {
            return View();
        }
    }
}

EtatSituation/Views/EdsArchive/Index.cshtml
@*********************************************
*****           EDS - Archive            *****
*********************************************@
    <div>
        @{
            @model EtatSituation.Models.EnteteEDS

            //Html.RenderPartial("_EnteteEDS", Model);
        }

        @* ENTETE *@
        <div class="col-md-4" id="divleft">
            <br />
            <p style="text-align:center"><img src="~/Images/logous1.png" /></p>
        </div>
        <div class="col-md-4" id="divcenter" style="text-align:center;">
            <br /><label id="lblTitre" class="textEDS">EDS - Archive</label><br />
            <label id="lblDate" class="textEDS"></label>  -  <label id="lblHeure" class="textEDS"></label>
        </div>
        <div class="col-md-2" id="divtemp" style="text-align:right;">
            @*<table align="right" id="tabletemp" style="width:100%">
                <tr align="center">
                    <td align="right"><label id="lblTemperature" class="textEDS"></label></td>
                    <td align="left"><img id="imgMeteo" width="55" height="55" /></td>
                </tr>
                <tr align="center">
                    <td colspan="2">
                        <label id="lblTemperatureRessentie" style="color: white;font-size: 20px;"></label><br />
                        <label id="lblInfo" class="TempEDS"></label>
                    </td>
                </tr>
            </table>*@
        </div>
        <div class="col-md-12" id="divActionPrev" style="padding:0px 0px 0px 0px;background-color:red;height:40px;text-align:center;visibility:collapse;display:none;width:100%">
            <label id="lblActionPrev" style="color:azure;font-weight:bold;font-size:30px">Urgences-Santé - Action de protection</label>
        </div>
        <div class="col-md-12" style="padding:0px 0px 0px 0px;width:100%">
            @*<marquee id="txtInfo" style="background-color:dimgrey;color:white;width:100%" class="textEDS">Urgences-Santé</marquee>*@
        </div>

        <div class="row">
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphCarteAppel.cshtml"); }
            </div>
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphVehDevoir.cshtml"); }
            </div>
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphAppelsAttenteAff.cshtml"); }
            </div>
        </div>

        <div class="row">
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphVolumeAppel.cshtml"); }
            </div>
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphSDDF.cshtml"); }
            </div>
            <div class="col-md-4 co_hide" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphRatio.cshtml"); }
            </div>
        </div>

    </div>

@*SI PAS ACCES*@
@*<div class="col-md-12" id="divMessageAcces" style="padding:0px 0px 0px 0px;background-color:blue;height:40px;text-align:center;width:100%">
        <label id="lblActionPrevAccesTitre" style="color:azure;font-weight:bold;font-size:30px">AUCUN ACCÈS À CETTE APPLICATION - @Model.User</label><br />
    </div>
    <div class="col-md-12" id="divMessageAcces" style="padding:0px 0px 0px 0px;background-color:blue;height:40px;text-align:center;width:100%">
        <label id="lblActionPrevAccesMsg" style="color:azure;font-weight:bold;font-size:30px">Contactez votre supérieur immédiat</label>
    </div>*@


<style type="text/css">
    .textEDS {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: white;
        font-size: 30px;
    }

    .TempEDS {
        font-size: 26px;
        color: white;
    }
</style>


<script src="~/GraphTheme.js"></script>
<script type="text/javascript">


    // FONCTION PRINCIPALE
    $(function () {

        Chargement();

    });

    // CHARGEMENT DES GRAPHIQUES

    function Chargement() {

         $.ajax({
            url: '@Url.Action("ChargementDonnees", "EdsArchive")',
            type: 'POST',
            async: true,
            dataType: "json",
            success: function (data) {
                GraphCarteAppel(data.CarteAppel);
                GraphVehDevoir(data.VehDevoir);
                GraphAppelsAttenteAff(data.AppelsAttenteAff);
                GraphVolumeAppel(data.VolumeAppel);
                GraphSDDF(data.SDDF);
                GraphRatio(data.Ratio);
                
            }
         });

    }

    function GraphRatio(data) {

    }



</script>