EtatSituation/Controllers/EdsGlobalController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using EtatSituation.Models;
using EtatSituation.API;
using System.Net.Http;
using System;
using Newtonsoft.Json;
using Microsoft.Ajax.Utilities;
using Microsoft.Owin.Security;
using System.Web;
using Microsoft.AspNet.Identity;

namespace EtatSituation.Controllers
{
    public class EdsGlobalController : Controller
    {
       
        public async Task<JsonResult> ChargementDonnees()
        {
            List<EdsDonnees> result = Eds.ObtenirDonneesEDS2("global");

            return Json(new
            {
                CarteAppel = result.Where(a => a.Indicateur.Contains("CarteAppel")).ToList(),
                VehDevoir = result.Where(a => a.Indicateur.Contains("VehDevoir")).ToList(), //VehDevoir  **tempo pour test
                AppelsAttenteAff = result.Where(a => a.Indicateur.Contains("AppelsAttenteAff")).ToList(),
                VolumeAppel = result.Where(a => a.Indicateur.Contains("VolumeAppel")).ToList(),
                SDDF = result.Where(a => a.Indicateur.Contains("SDDF")).ToList(),
                Ratio = result.Where(a => a.Indicateur.Contains("Ratio")).ToList(),
                ActionPreventive = result.Where(a => a.Indicateur.Contains("ActionPreventive")).ToList(),
                QuotaEffectifs = result.Where(a => a.Indicateur.Contains("QuotaEffectifs")).ToList()

            });
        }

        public async Task<JsonResult> ChargementMeteo()
        {
            Meteo.MeteoResult meteoResult = Eds.ObtenirMeteo();

            return Json(new
            {
                icon = meteoResult.currently.icon,
                summary = meteoResult.currently.summary,
                temperature = meteoResult.currently.temperature,
                apparentTemperature = meteoResult.currently.apparentTemperature
            });

        }

        // GET: EdsGlobal
        public ActionResult Index()
        {
            // Chargement de l'entete
            List<EdsDonnees> result = Eds.ObtenirDonneesEDS2("global");
            var entete = result.Where(a => a.Indicateur.Contains("Entete")).ToList();

           


            string user = "";
            if (HttpContext.Session["code_user"] != null)
            {
                user = HttpContext.Session["code_user"].ToString();
            }


            EnteteEDS objEntete = new EnteteEDS { Titre = entete[0].Details, User = user };

            return View(objEntete);
        }
    }
}

EtatSituation/Views/EdsGlobal/Index.cshtml
@*********************************************
    *****           EDS - GLOBAL             *****
    *********************************************@

    <div>
        @{
            @model EtatSituation.Models.EnteteEDS

            Html.RenderPartial("_EnteteEDS", Model);
        }
        <div class="row">
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphCarteAppel.cshtml"); }
            </div>
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphVehDevoir.cshtml"); }
            </div>
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphAppelsAttenteAff.cshtml"); }
            </div>
        </div>

        <div class="row">
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphVolumeAppel.cshtml"); }
            </div>
            <div class="col-md-4" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphSDDF.cshtml"); }
            </div>
            <div class="col-md-4 co_hide" style="text-align:center">
                @{ Html.RenderPartial("~/Views/Shared/Graphiques/_GraphRatio.cshtml"); }
            </div>
        </div>
        <p>user: @Model.User</p>
        <p>serveur: @Server.MachineName</p>

    </div>



@*SI PAS ACCES*@
@*<div class="col-md-12" id="divMessageAcces" style="padding:0px 0px 0px 0px;background-color:blue;height:40px;text-align:center;width:100%">
        <label id="lblActionPrevAccesTitre" style="color:azure;font-weight:bold;font-size:30px">AUCUN ACCÈS À CETTE APPLICATION - @Model.User</label><br />
    </div>
    <div class="col-md-12" id="divMessageAcces" style="padding:0px 0px 0px 0px;background-color:blue;height:40px;text-align:center;width:100%">
        <label id="lblActionPrevAccesMsg" style="color:azure;font-weight:bold;font-size:30px">Contactez votre supérieur immédiat</label>
    </div>*@


<style type="text/css">
    .textEDS {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: white;
        font-size: 30px;
    }

    .TempEDS {
        font-size: 26px;
        color: white;
    }
</style>


<script src="~/GraphTheme.js"></script>
<script type="text/javascript">


    // FONCTION PRINCIPALE
    $(function () {

        Chargement();

    });


    // CHARGEMENT DES GRAPHIQUES

    function Chargement() {

         $.ajax({
            url: '@Url.Action("ChargementDonnees", "EdsGlobal")',
            type: 'POST',
            async: true,
            dataType: "json",
            success: function (data) {
                GraphCarteAppel(data.CarteAppel);
                GraphVehDevoir(data.VehDevoir);
                GraphAppelsAttenteAff(data.AppelsAttenteAff);
                GraphVolumeAppel(data.VolumeAppel);
                GraphSDDF(data.SDDF);
                GraphRatio(data.Ratio);
                AffInfoEntete(data.ActionPreventive, data.QuotaEffectifs);
            }
         });

        //1 minute
        window.setTimeout("Chargement()", 60000);

    }

</script>