EtatSituation/Models/EnteteEDS.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EtatSituation.Models
{
    public class EnteteEDS
    {
        public string Titre { get; set; }
        public string User { get; set; }

    }
}

EtatSituation/Controllers/Eds911Controller.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using EtatSituation.Models;
using EtatSituation.API;
using System.Web.UI.WebControls;

namespace EtatSituation.Controllers
{
    public class Eds911Controller : Controller
    {

        public async Task<JsonResult> ChargementDonnees()
        {
            List<EdsDonnees> result = Eds.ObtenirDonneesEDS2("911");

            return Json(new
            {
                CarteAppel = result.Where(a => a.Indicateur.Contains("CarteAppel")).ToList(),
                VehDevoir = result.Where(a => a.Indicateur.Contains("VehDevoir")).ToList(), //VehDevoir  **tempo pour test
                AppelsAttenteAff = result.Where(a => a.Indicateur.Contains("AppelsAttenteAff")).ToList(),
                VolumeAppel = result.Where(a => a.Indicateur.Contains("VolumeAppel")).ToList(),
                SDDF = result.Where(a => a.Indicateur.Contains("SDDF")).ToList(),
                Ratio = result.Where(a => a.Indicateur.Contains("Ratio")).ToList(),
                ActionPreventive = result.Where(a => a.Indicateur.Contains("ActionPreventive")).ToList(),
                QuotaEffectifs = result.Where(a => a.Indicateur.Contains("QuotaEffectifs")).ToList()         
            });
        }

        public async Task<JsonResult> ChargementMeteo()
        {
            Meteo.MeteoResult meteoResult = Eds.ObtenirMeteo();

            return Json(new
            {
                icon = meteoResult.currently.icon,
                summary = meteoResult.currently.summary,
                temperature = meteoResult.currently.temperature,
                apparentTemperature = meteoResult.currently.apparentTemperature
            }); 

        }

        // GET: Eds911
        public ActionResult Index()
        {
            // Chargement de l'entete
            List<EdsDonnees> result = Eds.ObtenirDonneesEDS2("911");
            var entete = result.Where(a => a.Indicateur.Contains("Entete")).ToList();
            EnteteEDS objEntete = new EnteteEDS { Titre = entete[0].Details };
            return View(objEntete);
        }

       



    }
}

EtatSituation/Views/Shared/_EnteteEDS.cshtml
<style type="text/css">

    .textEDS {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: white;
        font-size: 30px;
    }

    .TempEDS {
        font-size: 26px;
        color: white;
    }

   
</style>


<div class="col-md-4" id="divleft">
    <br />
    <a href="~/Home/Index ">
        <p style="text-align:center"><img src="~/Images/logous1.png" /></p>
    </a>
</div>
<div class="col-md-4" id="divcenter" style="text-align:center;">
    <br /><label id="lblTitre" class="textEDS">@Model.Titre</label><br />
    <label id="lblDate" class="textEDS"></label>  -  <label id="lblHeure" class="textEDS"></label>
</div>
<div class="col-md-2" id="divtemp" style="text-align:right;">
    <table align="right" id="tabletemp" style="width:100%">
        <tr align="center">
            <td align="right"><label id="lblTemperature" class="textEDS"></label></td>
            <td align="left"><img id="imgMeteo" width="55" height="55" /></td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <label id="lblTemperatureRessentie" style="color: white;font-size: 20px;"></label><br />
                <label id="lblInfo" class="TempEDS"></label>
            </td>
        </tr>
    </table>
</div>
<div class="col-md-12" id="divActionPrev" style="padding:0px 0px 0px 0px;background-color:red;height:40px;text-align:center;display:none;width:100%">
    <label id="lblActionPrev" style="color:azure;font-weight:bold;font-size:30px">Urgences-Santé - Action de protection</label>
</div>
<div class="col-md-12" style="padding:0px 0px 0px 0px;width:100%">
    <marquee id="txtInfo" style="background-color:dimgrey;color:white;width:100%" class="textEDS">Urgences-Santé</marquee>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        DateTime();
        Meteo();
    })


    function DateTime() {

        var now = new Date(), // current date
            months = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']; // you get the idea

        var heure = now.getHours();
        var minute = now.getMinutes();
        var second = now.getSeconds();
        if (heure.toString().length < 2) {
            heure = '0' + heure;
        }
        if (minute.toString().length < 2) {
            minute = '0' + minute;
        }
        if (second.toString().length < 2) {
            second = '0' + second;
        }
        time = heure + ':' + minute + ':' + second,

            date = [now.getDate(),
            months[now.getMonth()],
            now.getFullYear()].join(' ');




        document.getElementById("lblDate").innerHTML = date;
        document.getElementById("lblHeure").innerHTML = time;


       window.setTimeout("DateTime()", 1000);


    }

    function AffInfoEntete(dtActPrev, dtQuotaEffectifs) {
     
        var message = "";
        var txtActPrevTitre = "";
        var txtDelai = "";

        // Action préventive
        if (dtActPrev.length > 0) {
            for (i = 0; i < dtActPrev.length; i++) {
                if (dtActPrev[i].Details == "Titre") {
                    txtActPrevTitre = dtActPrev[i].Texte1;
                }
                if (dtActPrev[i].Details == "Details") {
                    txtDelai = dtActPrev[i].Texte1;
                }
            }
        }

        // messages quota des effectifs
        if (dtQuotaEffectifs.length > 0) {
            message = dtQuotaEffectifs[0].Texte1;
        }

        // message action preventive et delai
        if (txtActPrevTitre !== "") {
            // activer l'action
            $('#divActionPrev').show();
            $('#lblActionPrev').text(txtActPrevTitre);

            // afficher le delai
            message = message + " " + txtDelai;
        }
        else {
            $('#divActionPrev').hide();
        }

        $('#txtInfo').text(message);
    }


    function Meteo() {
       
            $.ajax({
                url: '@Url.Action("ChargementMeteo", "Eds911")',
                type: 'POST',
                async: true,
                dataType: "json",
                success: function (data) {

                    $('#imgMeteo').attr("src", '/Images/meteo/' + data.icon + '.png');
                    document.getElementById("lblInfo").innerHTML = data.summary
                    document.getElementById("lblTemperature").innerHTML = Math.round(data.temperature) + '°C';
                    document.getElementById("lblTemperatureRessentie").innerHTML = 'ressentie : ' + Math.round(data.apparentTemperature) + '°C';

                }
            });

            // A chaque 30 minutes
            window.setTimeout("Meteo()", 1800000);
        }


</script>

EtatSituation/Views/Shared/_EnteteSansMessage.cshtml
<style type="text/css">

    .textEDS {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        color: white;
        font-size: 30px;
    }

    .TempEDS {
        font-size: 26px;
        color: white;
    }

   
</style>


<div class="col-md-4" id="divleft">
    <br />  <a href="~/Home/Index ">
        <p style="text-align:center"><img src="~/Images/logous1.png" /></p>
    </a>
</div>
<div class="col-md-4" id="divcenter" style="text-align:center;">
    <br /><label id="lblTitre" class="textEDS">@Model.Titre</label><br />
    <label id="lblDate" class="textEDS"></label>  -  <label id="lblHeure" class="textEDS"></label>
</div>
<div class="col-md-2" id="divtemp" style="text-align:right;">
    <table align="right" id="tabletemp" style="width:100%">
        <tr align="center">
            <td align="right"><label id="lblTemperature" class="textEDS"></label></td>
            <td align="left"><img id="imgMeteo" width="55" height="55" /></td>
        </tr>
        <tr align="center">
            <td colspan="2">
                <label id="lblTemperatureRessentie" style="color: white;font-size: 20px;"></label><br />
                <label id="lblInfo" class="TempEDS"></label>
            </td>
        </tr>
    </table>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        DateTime();
        Meteo();
    })


    function DateTime() {

        var now = new Date(), // current date
            months = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']; // you get the idea

        var heure = now.getHours();
        var minute = now.getMinutes();
        var second = now.getSeconds();
        if (heure.toString().length < 2) {
            heure = '0' + heure;
        }
        if (minute.toString().length < 2) {
            minute = '0' + minute;
        }
        if (second.toString().length < 2) {
            second = '0' + second;
        }
        time = heure + ':' + minute + ':' + second,

            date = [now.getDate(),
            months[now.getMonth()],
            now.getFullYear()].join(' ');




        document.getElementById("lblDate").innerHTML = date;
        document.getElementById("lblHeure").innerHTML = time;


       window.setTimeout("DateTime()", 1000);


    }

    function AffInfoEntete(dtActPrev, dtQuotaEffectifs) {
     
        var message = "";
        var txtActPrevTitre = "";
        var txtDelai = "";

        // Action préventive
        if (dtActPrev.length > 0) {
            for (i = 0; i < dtActPrev.length; i++) {
                if (dtActPrev[i].Details == "Titre") {
                    txtActPrevTitre = dtActPrev[i].Texte1;
                }
                if (dtActPrev[i].Details == "Details") {
                    txtDelai = dtActPrev[i].Texte1;
                }
            }
        }

        // messages quota des effectifs
        if (dtQuotaEffectifs.length > 0) {
            message = dtQuotaEffectifs[0].Texte1;
        }

        // message action preventive et delai
        if (txtActPrevTitre !== "") {
            // activer l'action
            $('#divActionPrev').show();
            $('#lblActionPrev').text(txtActPrevTitre);

            // afficher le delai
            message = message + " " + txtDelai;
        }
        else {
            $('#divActionPrev').hide();
        }

        $('#txtInfo').text(message);
    }


    function Meteo() {
       
            $.ajax({
                url: '@Url.Action("ChargementMeteo", "Eds911")',
                type: 'POST',
                async: true,
                dataType: "json",
                success: function (data) {

                    $('#imgMeteo').attr("src", '/Images/meteo/' + data.icon + '.png');
                    document.getElementById("lblInfo").innerHTML = data.summary
                    document.getElementById("lblTemperature").innerHTML = Math.round(data.temperature) + '°C';
                    document.getElementById("lblTemperatureRessentie").innerHTML = 'ressentie : ' + Math.round(data.apparentTemperature) + '°C';

                }
            });

            // A chaque 30 minutes
            window.setTimeout("Meteo()", 1800000);
        }


</script>

EtatSituation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Tableau - État de situation</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/highcharts")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="~/Scripts/bootstrap.js"></script>
        <link href="~/Content/bootstrap.css" rel="stylesheet" />*@
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <link href="~/Content/BoutonOnOff.css" rel="stylesheet" />
  
  

    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />




</head>
<body style="background-color:#222;padding:0px 0px 0px 0px;">
   

    <div>
        @RenderBody()
    </div>


  
    @RenderSection("scripts", required: false)





</body>
</html>